### ISSUE TITLE
Can't generate invoice

### ISSUE THREAD

**Issue by PedroTerriquez** [lacf95/automatic-sat#8]
Since this month I can't generate my invoice, seems like SAT page developers delete a link.

```
Starting automatic-sat_selenium_1 ... done
The Gemfile's dependencies are satisfied
  Successfully built RubyGem
  Name: automatic-sat
  Version: 0.0.1
  File: automatic-sat-0.0.1.gem
Successfully installed automatic-sat-0.0.1
1 gem installed
2019-10-30 17:48:51 WARN Selenium [DEPRECATION] :firefox_profile capabilitiy is deprecated. Use Selenium::WebDriver::Firefox::Options#profile instead.
2019-10-30 17:48:51 WARN Selenium [DEPRECATION] :firefox_profile capabilitiy is deprecated. Use Selenium::WebDriver::Firefox::Options#profile instead.
Traceback (most recent call last):
        26: from generate_invoices.rb:10:in `<main>'
        25: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/file_iterator.rb:14:in `iterate'
        24: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/file_iterator.rb:14:in `each'
        23: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/file_iterator.rb:15:in `block in iterate'
        22: from generate_invoices.rb:11:in `block in <main>'
        21: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:15:in `generate_invoices'
        20: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:15:in `each'
        19: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:17:in `block in generate_invoices'
        18: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:17:in `each'
        17: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:19:in `block (2 levels) in generate_invoices'
        16: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat.rb:33:in `generate_invoice'
        15: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/invoice.rb:12:in `create'
        14: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/invoice.rb:25:in `visit_create_invoice_page'
        13: from /bundle/gems/automatic-sat-0.0.1/lib/automatic_sat/invoice.rb:33:in `visit_main_invoice_page'
        12: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/search_context.rb:62:in `find_element'
        11: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/w3c/bridge.rb:547:in `find_element_by'
        10: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
         9: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
         8: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
         7: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
         6: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
         5: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
         4: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
         3: from /bundle/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
         2: from element.find/</<@chrome://marionette/content/element.js:339:16
         1: from NoSuchElementError@chrome://marionette/content/error.js:389:5
WebDriverError@chrome://marionette/content/error.js:179:5: Unable to locate element: a[alt="/personas/factura-electronica"] (Selenium::WebDriver::Error::NoSuchElementError)
```

I wil change the way we visit the invoice generator page.

**Comment by lacf95** [comment]
Thank you, @PedroTerriquez 
This is solved
